doc.type.html
script
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=documentgetelementbyid(header)
src.appendchild(this.img)
filename=covidstrings22.js
java.awt graphics 
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new button (change color)
public fun with graphics(){
color panel=new j panel();
add (panel,center )
button panel=
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
num teams
total players=players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args){
jframe f = new covid strings22()
f.set title(covid strings22)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten 
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object{a:1,b:2,c:3,d:4,e:5,f:6,g:7,h:8}
keys object keys(team)
entries object entries(obj);
value object=[team color]
covidstrings team list22=[violet relivers,green peacemakers,indigo isos,white transit angels ,yellow moxie,pink covid disease fighters,purple brave hearts,black night riders]
covid strings phrase list22=[non-concatenated strings "gargle with salt water may help with covid"
"the best prevention  mechanism might just be get vaccinated"
"it helps that covid vaccines do not mess with your dna"
"even though garlic may help kill vampires it is not a covid treatment"
"the same is true for crucifixes"
"dont even think that extreme cold weather will help reduce covid"
"if past respiratory virus behavior is prologue cold weather might actually accelerate covid"
"while milk itself is not an effective covid treatment mixing it with an antihistamine in benadryl helps"
concatenated strings
"just"+"like"+"apple"+"c"+"car"+"does"+"not"+"mean"+"self"+"driving"+"superspreader"+"model"+"c"+"does"+"not"+"mean"+"covid"+"model"
"in"+"a"+"different"+"way"+"car"+"prices"+"have"+"increased"+"due"+"to"+"covid"
"covid"+"babies"+"have"+"on"+"the"+"other"+"hand"+"very"+"beneficial"+"traits"
"the"+"bad"+"news"+"is"+"that"+"trump"+"wants"+"to"+"tie"+"federal"+"funding"+"for"+"schools"+"to"+"not"+"mandating"+"covid"+"vaccines"
"this"+"includes"+"the"+"fact"+"that"+"trump"+"wanted"+"to"+"reopen"+"schools"+"early"
"ironically"+"most"+"schools"+"dropped"+"vaccine"+"requirements"+"in"+"2022"
"one"+"sign"+"overall"+"towards"+"normalcy"+"is"+"when"+"science"+"makes"+"clear"+"that"+"the"+"risk"+"can"+"be"+"something"+"people"+"overall"+"can"+"deal"+"with"
"for"+"example"+"endemic"+"covid"+"would"+"require"+"adjustments"+"like"+"masking"+"if"+"youre"+"sick"+"but"+"no"+"lockdowns"]
covid strings22multiplechoicelist=[1a prevention b removal c voting d immunity,2:a c9 corvette b c car c i car d lincoln park,3:a salt water b hydrogen peroxide c bath salt d italian twinkle lights,4:a toilet paper b car prices c kn95 masks d prank calls,5:a covid b sun-tanning c skin cancer d werewolf,6:a school bus drivers b state capture c federal funding d ukraine aid,7:a rna b 401k c dna d atm,8:aschools b offices c movie theaters d mar-a-lago,9:a bibles b crucifixes c torahs d quarans,10:a disappointing b average c beneficial d honest,11:a young blood b cold weather c hot weather d muggification,12:a 2011 b 1975 c 2014 d 2022,13:a thrown out the window b prologue c taken literally but not seriously d the boy who cried wolf,14:a science b politics c addiction d mild infections,15:a pre-pandemic b pandemic c endemic d panendemic,16:a milk b tea c ginger beer d xanax]
covidstrings22mathproblemslist=[ non-concatenated "if a graph showing the price of cars post covid increased by200 percent if the y intercept is100 what is the y coordinate at1"?,"if the previous point was reflected across the x axis  what is the new point?”,“if the solution to the previous problem was rotated 180 degrees counterclockwise what would the new point be?”, “if another point was at 400 find the x coordinate?”, “if a smaller line had ½ the slope of the previous line what is the new post-covid  price of a car at the x point of  6?”,“if a graph regarding covid and milk had a slope of 1/5 and a y intercept of 2 what would the y point be if the x point is 3?”,“if the line stays flat what is the relationship between covid and milk?”,“if the line regarding covid and car prices continues to increase what would the relationship between covid and car prices be"?,
concatenated "if"+"87"+"percent"+"believe"+"that"+"covid"+"caused"+"an"+"increase"+"in"+"car"+"prices"+"what"+"percent"+"dont"?,"if"+"67"+"percent"+"strongly"+"believe"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"11"+"percent"+"what"+"is"+"the"+"range"?,"if"+"14"+"percent"+"believe"+"weather"+"doesnt"+"impact"+"covid"+"transmission"+"what"+"percent"+"do"?,"if"+"9"+"percent"+"strongly"+"believe"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"3.11"+"percent"+"what"+"is"+"the"+"range"?]
covid strings scrambled phraselist22=["divoc"+"matineantihist","ovcid"+"dolc"+"theawr"]
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
public.boolean isscramble
if (s1.length())!=s2.length() or s3.length()
return false
if (s1.length()) ==s2 or s3 
return true
char[]arr1=s1.tochararray
char[]arr2=s2.tochararray
char[] arr3=s3.tochararray
arrays.sort(arr1)
arrays.sort(arr2)
arrays.sort(arr3)
if(!new string(arr1).equals(new string(arr2)))
return false
for(int i=1; i<s1.length();i++)} 
string11=s1.substring(0,i)
strings12=s1.substring(i,s1.length()-i);
strings21=s2.substring(0,i)
string22=s2.substring(0,s2.length()-i);
string23=s2.substring(0,s2.length()-i ());
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
x1=0
y1=100
x2=1
y2=102
x3=2x+y3-100
y3=400
stop offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fecomponenttransfer>
<fefunccovidstrings  type=linear slope>=1
transformationlist=[reflection,rotation,translation]
if reflection (1,102)==x axis:
change y coordinate 
else:
remain
if rotation(1,-102)==180 degrees:
shift 180 degrees
else:
remain 
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
x1=0
y1=2
x2=3
y2=2 
stop offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
eidth=100%
height=100%
<fecomponenttransfer>
<defunccovidstrings  type=linear slope<=1
function1=(covid,milk)
if function1.slope==0:
return no relationship
else:
return direct or inverse 
function2=(covid,car prices) 
if function2.slope x1*y1 +=1:
return direct
else:
return inverse or no relationship
ifselectedanswer=correct:
return true
else:
return false
if selectedanswer=not correct
return false
else 
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet)
if users team wins covid strings22 
console log users team wins covid strings22 
else
return game over
return filename
