doc.type.html
script
filename=covid strings 22 key words.js
covid strings 22 key word list=[best mechanism vaccinations,apple car,gargle,increased,not treatment,not mandating covid vaccines, do not mess,reopen early,same true,covid babies,extreme reduce covid,schools dropped vaccine requirements,cold weather,normalcy,require adjustments,mixing it with benadryl]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
covid strings 22 reference list=[a:best defense against covid-19 is vaccine |ucla health,b:apple car:its the end of the road,but heres what could have happened |techradar,c:this old-fashioned remedy may ease covid:gargle with salt water(msn.com),d:car prices increase during covid-19 over high demand,low supply(businessinsider.com),e:fake coronavirus cures, part 2:garlic isnt a cure-fact check.org,f:trump threatens to cut federal funds from schools that dont reopen -politico,g:no,covid mrna vaccines wont damage your dna |scientific american,h:the trump administration pushes to reopen schools in the fall:npr,
i:list of unproven methods against covid-19 -wikipedia,covid pandemic babies show fascinating biological quirk and very beneficial trait,study finds(msn.com),j:does extreme heat or cold kill coronavirus? |huffpost life,k:vaccines for covid-19 arent required in schools this fall-vox,l:cold and dry winter conditions are associated with greater sars-cov-2 transmission at regional level in western countries during the first epidemic wave|scientific reports (nature.com),m:this phase of pandemic is when life returns to normal:essay |time,n:what living with endemic covid will look like in 2022 and future (cnbc.com),o:can milk cure covid-19? not exactly but a new treatment shows promise|the hill]
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script Foobar =This Entity
Entity Reparnet (This.Entity)
I=Pc.CreateScript(I);
I.Attributes.Add(Foobar,{Type:Entity});
I.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
J=Pc.CreateScript(J);
J.Attributes.Add(Foobar,{Type:Entity});
J.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
K=Pc.CreateScript(K);
K.Attributes.Add(Foobar,{Type:Entity});
K.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset=This App .Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
L =Pc.CreateScript(L);
L.Attributes.Add(Foobar,{Type:Entity});
L.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize=function() 
console.log(this.foobar.name);
return filename































